url = "https://admin-demo.nopcommerce.com/login?ReturnUrl=%2Fadmin%2F"
input_email_box_xpath = "//input[@id='Email']"
input_password_box_xpath = "//input[@id='Password']"
click_on_signin_button_xpath = "//button[text()='Log in']"
click_on_logout_button_xpath = "//a[text()='Logout']"
Click_on_customer_main_menu_xpath = "//a[@href ='#']//p[contains(text(), 'Customers' )]"
click_on_customer_sub_menu_xpath = "//a[@href='/Admin/Customer/List']"
click_on_add_new_button_xpath = "//a[@class='btn btn-primary']"
click_on_Email_xpath = "//input[@id='Email']"
click_on_Password_xpath = "//input[@id='Password']"
click_on_first_name_xpath = "//input[@id='FirstName']"
click_on_last_name_xpath = "//input[@id='LastName']"
click_on_gender_male_xpath = "//input[@id='Gender_Male']"
click_on_gender_female_xpath = "//input[@id='Gender_Female']"
click_on_date_picker_xpath = "//input[@id='DateOfBirth']"
click_on_news_letter_xpath = "//div[@class='input-group-append']//div[@role='listbox']"
click_on_test_store2_xpath = "//li[text()='Test store 2']"
click_on_company_name_xpath = "//input[@id='Company']"
click_on_Customers_role_xpath = "(//div[@role='listbox'])[1]"
click_on_Administrator_xpath = "//li[text()='Administrators']"
click_on_Guests_xpath = "//li[text()='Guests']"
click_on_Registered_xpath = "//li[text()='Registered']"
click_on_vendors_xpath = "//li[text()='Vendors']"
click_on_manager_vendor_xpath = "//select[@id='VendorId']"
click_on_Admin_content_xpath = "//textarea[@id='AdminComment']"
click_on_save_button_xpath = "//button[@name='save']"
